In [1]:
import pandas as pd
import numpy as np
import time
from IPython.display import display, Markdown

print("MetricMind - Week 1")
print("Libraries loaded successfully!")

MetricMind - Week 1
Libraries loaded successfully!

In [2]:
customers = pd.DataFrame({
    "customer_id": [
        "C001", "C002", "C003", "C004", "C005",
        "C006", "C007", "C008", "C009", "C010"
    ],
    
    "customer_name": [
        "Acme Corporation",
        "Globex Industries",
        "Initech",
        "Stark Technologies",
        "Wayne Enterprises",
        "Wonka Foods",
        "Umbrella Retail",
        "Hooli Systems",
        "Tyrell Corporation",
        "Massive Dynamic"
    ],
    
    "segment": [
        "Enterprise", "Enterprise", "SMB", "Enterprise", "Enterprise",
        "SMB", "SMB", "Enterprise", "Enterprise", "SMB"
    ],
    
    "region": [
        "North", "West", "South", "East", "North",
        "West", "South", "East", "West", "North"
    ],
    
    "country": [
        "USA", "USA", "USA", "USA", "USA",
        "USA", "USA", "USA", "USA", "USA"
    ]
})

display(customers)

  customer_id       customer_name     segment region country
0        C001    Acme Corporation  Enterprise  North     USA
1        C002   Globex Industries  Enterprise   West     USA
2        C003             Initech         SMB  South     USA
3        C004  Stark Technologies  Enterprise   East     USA
4        C005   Wayne Enterprises  Enterprise  North     USA
5        C006         Wonka Foods         SMB   West     USA
6        C007     Umbrella Retail         SMB  South     USA
7        C008       Hooli Systems  Enterprise   East     USA
8        C009  Tyrell Corporation  Enterprise   West     USA
9        C010     Massive Dynamic         SMB  North     USA

In [3]:
products = pd.DataFrame({
    "product_id": [
        "P001", "P002", "P003", "P004",
        "P005", "P006", "P007", "P008"
    ],
    
    "product_name": [
        "Analytics Platform",
        "Cloud Storage",
        "Data Warehouse",
        "BI Dashboard",
        "AI Assistant",
        "Data Pipeline",
        "Security Suite",
        "CRM Integration"
    ],
    
    "category": [
        "Software",
        "Cloud",
        "Cloud",
        "Analytics",
        "AI",
        "Engineering",
        "Security",
        "Integration"
    ],
    
    "unit_price": [
        1200,
        800,
        2500,
        1500,
        3000,
        2200,
        1800,
        1100
    ]
})

display(products)

  product_id        product_name     category  unit_price
0       P001  Analytics Platform     Software        1200
1       P002       Cloud Storage        Cloud         800
2       P003      Data Warehouse        Cloud        2500
3       P004        BI Dashboard    Analytics        1500
4       P005        AI Assistant           AI        3000
5       P006       Data Pipeline  Engineering        2200
6       P007      Security Suite     Security        1800
7       P008     CRM Integration  Integration        1100

In [4]:
orders = pd.DataFrame({
    "order_id": [
        "O001", "O002", "O003", "O004", "O005",
        "O006", "O007", "O008", "O009", "O010",
        "O011", "O012", "O013", "O014", "O015"
    ],
    
    "customer_id": [
        "C001", "C002", "C003", "C004", "C005",
        "C006", "C007", "C008", "C009", "C010",
        "C001", "C002", "C003", "C004", "C005"
    ],
    
    "product_id": [
        "P001", "P003", "P004", "P005", "P006",
        "P002", "P007", "P001", "P005", "P004",
        "P003", "P005", "P008", "P007", "P001"
    ],
    
    "order_date": [
        "2026-01-05", "2026-01-08", "2026-01-12",
        "2026-01-15", "2026-01-20", "2026-02-02",
        "2026-02-07", "2026-02-11", "2026-02-18",
        "2026-02-25", "2026-03-03", "2026-03-10",
        "2026-03-14", "2026-03-18", "2026-03-25"
    ],
    
    "quantity": [
        5, 2, 3, 4, 2,
        5, 3, 6, 2, 4,
        1, 3, 5, 2, 4
    ],
    
    "discount": [
        0.05, 0.10, 0.00, 0.05, 0.10,
        0.00, 0.05, 0.10, 0.00, 0.05,
        0.00, 0.10, 0.05, 0.00, 0.05
    ]
})

orders["order_date"] = pd.to_datetime(orders["order_date"])

display(orders)

   order_id customer_id product_id order_date  quantity  discount
0      O001        C001       P001 2026-01-05         5      0.05
1      O002        C002       P003 2026-01-08         2      0.10
2      O003        C003       P004 2026-01-12         3      0.00
3      O004        C004       P005 2026-01-15         4      0.05
4      O005        C005       P006 2026-01-20         2      0.10
5      O006        C006       P002 2026-02-02         5      0.00
6      O007        C007       P007 2026-02-07         3      0.05
7      O008        C008       P001 2026-02-11         6      0.10
8      O009        C009       P005 2026-02-18         2      0.00
9      O010        C010       P004 2026-02-25         4      0.05
10     O011        C001       P003 2026-03-03         1      0.00
11     O012        C002       P005 2026-03-10         3      0.10
12     O013        C003       P008 2026-03-14         5      0.05
13     O014        C004       P007 2026-03-18         2      0.00
14     O015        C005       P001 2026-03-25         4      0.05

In [5]:
raw_customers = customers.copy()
raw_products = products.copy()
raw_orders = orders.copy()

print("RAW LAYER")
print("-" * 40)

print("Customers:", raw_customers.shape)
print("Products :", raw_products.shape)
print("Orders   :", raw_orders.shape)

RAW LAYER
----------------------------------------
Customers: (10, 5)
Products : (8, 4)
Orders   : (15, 6)

In [6]:
print("CUSTOMER MISSING VALUES")
print(raw_customers.isnull().sum())

print("\nPRODUCT MISSING VALUES")
print(raw_products.isnull().sum())

print("\nORDER MISSING VALUES")
print(raw_orders.isnull().sum())

CUSTOMER MISSING VALUES
customer_id      0
customer_name    0
segment          0
region           0
country          0
dtype: int64

PRODUCT MISSING VALUES
product_id      0
product_name    0
category        0
unit_price      0
dtype: int64

ORDER MISSING VALUES
order_id       0
customer_id    0
product_id     0
order_date     0
quantity       0
discount       0
dtype: int64

In [7]:
stg_customers = raw_customers.copy()

stg_customers["customer_name"] = (
    stg_customers["customer_name"]
    .str.strip()
)

stg_customers["segment"] = (
    stg_customers["segment"]
    .str.strip()
    .str.upper()
)

stg_customers["region"] = (
    stg_customers["region"]
    .str.strip()
    .str.upper()
)

stg_customers["country"] = (
    stg_customers["country"]
    .str.strip()
    .str.upper()
)

display(stg_customers)

  customer_id       customer_name     segment region country
0        C001    Acme Corporation  ENTERPRISE  NORTH     USA
1        C002   Globex Industries  ENTERPRISE   WEST     USA
2        C003             Initech         SMB  SOUTH     USA
3        C004  Stark Technologies  ENTERPRISE   EAST     USA
4        C005   Wayne Enterprises  ENTERPRISE  NORTH     USA
5        C006         Wonka Foods         SMB   WEST     USA
6        C007     Umbrella Retail         SMB  SOUTH     USA
7        C008       Hooli Systems  ENTERPRISE   EAST     USA
8        C009  Tyrell Corporation  ENTERPRISE   WEST     USA
9        C010     Massive Dynamic         SMB  NORTH     USA

In [8]:
stg_products = raw_products.copy()

stg_products["product_name"] = (
    stg_products["product_name"]
    .str.strip()
)

stg_products["category"] = (
    stg_products["category"]
    .str.strip()
    .str.upper()
)

stg_products["unit_price"] = (
    stg_products["unit_price"]
    .astype(float)
)

display(stg_products)

  product_id        product_name     category  unit_price
0       P001  Analytics Platform     SOFTWARE      1200.0
1       P002       Cloud Storage        CLOUD       800.0
2       P003      Data Warehouse        CLOUD      2500.0
3       P004        BI Dashboard    ANALYTICS      1500.0
4       P005        AI Assistant           AI      3000.0
5       P006       Data Pipeline  ENGINEERING      2200.0
6       P007      Security Suite     SECURITY      1800.0
7       P008     CRM Integration  INTEGRATION      1100.0

In [9]:
stg_orders = raw_orders.copy()

stg_orders["order_id"] = (
    stg_orders["order_id"]
    .str.strip()
)

stg_orders["customer_id"] = (
    stg_orders["customer_id"]
    .str.strip()
)

stg_orders["product_id"] = (
    stg_orders["product_id"]
    .str.strip()
)

stg_orders["quantity"] = (
    stg_orders["quantity"]
    .astype(int)
)

stg_orders["discount"] = (
    stg_orders["discount"]
    .astype(float)
)

display(stg_orders)

   order_id customer_id product_id order_date  quantity  discount
0      O001        C001       P001 2026-01-05         5      0.05
1      O002        C002       P003 2026-01-08         2      0.10
2      O003        C003       P004 2026-01-12         3      0.00
3      O004        C004       P005 2026-01-15         4      0.05
4      O005        C005       P006 2026-01-20         2      0.10
5      O006        C006       P002 2026-02-02         5      0.00
6      O007        C007       P007 2026-02-07         3      0.05
7      O008        C008       P001 2026-02-11         6      0.10
8      O009        C009       P005 2026-02-18         2      0.00
9      O010        C010       P004 2026-02-25         4      0.05
10     O011        C001       P003 2026-03-03         1      0.00
11     O012        C002       P005 2026-03-10         3      0.10
12     O013        C003       P008 2026-03-14         5      0.05
13     O014        C004       P007 2026-03-18         2      0.00
14     O015        C005       P001 2026-03-25         4      0.05

In [10]:
sales_model = stg_orders.merge(
    stg_customers,
    on="customer_id",
    how="left"
)

sales_model = sales_model.merge(
    stg_products,
    on="product_id",
    how="left"
)

display(sales_model)

,order_id,customer_id,product_id,order_date,quantity,discount,customer_name,segment,region,country,product_name,category,unit_price
0,O001,C001,P001,2026-01-05,5,0.05,Acme Corporation,ENTERPRISE,NORTH,USA,Analytics Platform,SOFTWARE,1200.0
1,O002,C002,P003,2026-01-08,2,0.10,Globex Industries,ENTERPRISE,WEST,USA,Data Warehouse,CLOUD,2500.0
2,O003,C003,P004,2026-01-12,3,0.00,Initech,SMB,SOUTH,USA,BI Dashboard,ANALYTICS,1500.0
3,O004,C004,P005,2026-01-15,4,0.05,Stark Technologies,ENTERPRISE,EAST,USA,AI Assistant,AI,3000.0
4,O005,C005,P006,2026-01-20,2,0.10,Wayne Enterprises,ENTERPRISE,NORTH,USA,Data Pipeline,ENGINEERING,2200.0
5,O006,C006,P002,2026-02-02,5,0.00,Wonka Foods,SMB,WEST,USA,Cloud Storage,CLOUD,800.0
6,O007,C007,P007,2026-02-07,3,0.05,Umbrella Retail,SMB,SOUTH,USA,Security Suite,SECURITY,1800.0
7,O008,C008,P001,2026-02-11,6,0.10,Hooli Systems,ENTERPRISE,EAST,USA,Analytics Platform,SOFTWARE,1200.0
8,O009,C009,P005,2026-02-18,2,0.00,Tyrell Corporation,ENTERPRISE,WEST,USA,AI Assistant,AI,3000.0
9,O010,C010,P004,2026-02-25,4,0.05,Massive Dynamic,SMB,NORTH,USA,BI Dashboard,ANALYTICS,1500.0
10,O011,C001,P003,2026-03-03,1,0.00,Acme Corporation,ENTERPRISE,NORTH,USA,Data Warehouse,CLOUD,2500.0
11,O012,C002,P005,2026-03-10,3,0.10,Globex Industries,ENTERPRISE,WEST,USA,AI Assistant,AI,3000.0
12,O013,C003,P008,2026-03-14,5,0.05,Initech,SMB,SOUTH,USA,CRM Integration,INTEGRATION,1100.0
13,O014,C004,P007,2026-03-18,2,0.00,Stark Technologies,ENTERPRISE,EAST,USA,Security Suite,SECURITY,1800.0
14,O015,C005,P001,2026-03-25,4,0.05,Wayne Enterprises,ENTERPRISE,NORTH,USA,Analytics Platform,SOFTWARE,1200.0

In [11]:
sales_model["gross_sales"] = (
    sales_model["quantity"]
    * sales_model["unit_price"]
)

sales_model["discount_amount"] = (
    sales_model["gross_sales"]
    * sales_model["discount"]
)

sales_model["net_sales"] = (
    sales_model["gross_sales"]
    - sales_model["discount_amount"]
)

display(
    sales_model[
        [
            "order_id",
            "customer_name",
            "product_name",
            "quantity",
            "gross_sales",
            "discount_amount",
            "net_sales"
        ]
    ]
)

,order_id,customer_name,product_name,quantity,gross_sales,discount_amount,net_sales
0,O001,Acme Corporation,Analytics Platform,5,6000.0,300.0,5700.0
1,O002,Globex Industries,Data Warehouse,2,5000.0,500.0,4500.0
2,O003,Initech,BI Dashboard,3,4500.0,0.0,4500.0
3,O004,Stark Technologies,AI Assistant,4,12000.0,600.0,11400.0
4,O005,Wayne Enterprises,Data Pipeline,2,4400.0,440.0,3960.0
5,O006,Wonka Foods,Cloud Storage,5,4000.0,0.0,4000.0
6,O007,Umbrella Retail,Security Suite,3,5400.0,270.0,5130.0
7,O008,Hooli Systems,Analytics Platform,6,7200.0,720.0,6480.0
8,O009,Tyrell Corporation,AI Assistant,2,6000.0,0.0,6000.0
9,O010,Massive Dynamic,BI Dashboard,4,6000.0,300.0,5700.0
10,O011,Acme Corporation,Data Warehouse,1,2500.0,0.0,2500.0
11,O012,Globex Industries,AI Assistant,3,9000.0,900.0,8100.0
12,O013,Initech,CRM Integration,5,5500.0,275.0,5225.0
13,O014,Stark Technologies,Security Suite,2,3600.0,0.0,3600.0
14,O015,Wayne Enterprises,Analytics Platform,4,4800.0,240.0,4560.0

In [12]:
metrics = {
    "total_revenue": sales_model["net_sales"].sum(),
    "total_orders": sales_model["order_id"].nunique(),
    "total_customers": sales_model["customer_id"].nunique(),
    "total_products": sales_model["product_id"].nunique(),
    "average_order_value": sales_model["net_sales"].mean()
}

print("METRICMIND SEMANTIC METRICS")
print("=" * 40)

for metric, value in metrics.items():
    print(f"{metric}: {value:,.2f}")

METRICMIND SEMANTIC METRICS
========================================
total_revenue: 81,355.00
total_orders: 15.00
total_customers: 10.00
total_products: 8.00
average_order_value: 5,423.67

In [13]:
revenue_by_region = (
    sales_model
    .groupby("region")["net_sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Revenue by Region")
print("=" * 30)

display(
    revenue_by_region
    .reset_index(name="revenue")
)

Revenue by Region
==============================

  region  revenue
0   WEST  22600.0
1  NORTH  22420.0
2   EAST  21480.0
3  SOUTH  14855.0

In [19]:
revenue_by_category = (
    sales_model
    .groupby("category")["net_sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Revenue by Product Category")
print("=" * 35)

display(
    revenue_by_category
    .reset_index(name="revenue")
)

Revenue by Product Category
===================================

      category  revenue
0           AI  25500.0
1     SOFTWARE  16740.0
2        CLOUD  11000.0
3    ANALYTICS  10200.0
4     SECURITY   8730.0
5  INTEGRATION   5225.0
6  ENGINEERING   3960.0

In [20]:
top_customers = (
    sales_model
    .groupby(
        ["customer_id", "customer_name"]
    )["net_sales"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

top_customers.columns = [
    "customer_id",
    "customer_name",
    "revenue"
]

print("Top Customers")
print("=" * 30)

display(top_customers.head(5))

Top Customers
==============================

  customer_id       customer_name  revenue
0        C004  Stark Technologies  15000.0
1        C002   Globex Industries  12600.0
2        C003             Initech   9725.0
3        C005   Wayne Enterprises   8520.0
4        C001    Acme Corporation   8200.0

In [21]:
print("METRICMIND DATA QUALITY CHECKS")
print("=" * 40)

checks = {
    "Customer IDs unique":
        stg_customers["customer_id"].is_unique,

    "Product IDs unique":
        stg_products["product_id"].is_unique,

    "Order IDs unique":
        stg_orders["order_id"].is_unique,

    "No missing customer IDs":
        stg_customers["customer_id"].notna().all(),

    "No missing product IDs":
        stg_products["product_id"].notna().all(),

    "No missing order IDs":
        stg_orders["order_id"].notna().all(),

    "No negative quantity":
        (stg_orders["quantity"] >= 0).all(),

    "No negative prices":
        (stg_products["unit_price"] >= 0).all()
}

for check, result in checks.items():
    status = "PASS" if result else "FAIL"
    print(f"{check}: {status}")

METRICMIND DATA QUALITY CHECKS
========================================
Customer IDs unique: PASS
Product IDs unique: PASS
Order IDs unique: PASS
No missing customer IDs: PASS
No missing product IDs: PASS
No missing order IDs: PASS
No negative quantity: PASS
No negative prices: PASS

In [22]:
print("=" * 55)
print("              METRICMIND WEEK 1")
print("          BUSINESS ANALYTICS SUMMARY")
print("=" * 55)

print(f"Total Revenue       : ${metrics['total_revenue']:,.2f}")
print(f"Total Orders        : {metrics['total_orders']}")
print(f"Total Customers     : {metrics['total_customers']}")
print(f"Total Products      : {metrics['total_products']}")
print(f"Average Order Value : ${metrics['average_order_value']:,.2f}")

print("=" * 55)

print("\nTOP 5 CUSTOMERS")
display(top_customers.head(5))

print("\nREVENUE BY REGION")
display(
    revenue_by_region.reset_index(
        name="revenue"
    )
)

=======================================================
              METRICMIND WEEK 1
          BUSINESS ANALYTICS SUMMARY
=======================================================
Total Revenue       : $81,355.00
Total Orders        : 15
Total Customers     : 10
Total Products      : 8
Average Order Value : $5,423.67
=======================================================

TOP 5 CUSTOMERS

  customer_id       customer_name  revenue
0        C004  Stark Technologies  15000.0
1        C002   Globex Industries  12600.0
2        C003             Initech   9725.0
3        C005   Wayne Enterprises   8520.0
4        C001    Acme Corporation   8200.0

REVENUE BY REGION

  region  revenue
0   WEST  22600.0
1  NORTH  22420.0
2   EAST  21480.0
3  SOUTH  14855.0

In [23]:
def metricmind_response(question):

    question = question.lower()

    if "total revenue" in question or "total sales" in question:
        return (
            f"The total revenue is "
            f"${metrics['total_revenue']:,.2f}."
        )

    elif "orders" in question:
        return (
            f"There are "
            f"{metrics['total_orders']} total orders."
        )

    elif "customers" in question:
        return (
            f"There are "
            f"{metrics['total_customers']} customers."
        )

    elif "products" in question:
        return (
            f"There are "
            f"{metrics['total_products']} products."
        )

    elif "average order" in question:
        return (
            f"The average order value is "
            f"${metrics['average_order_value']:,.2f}."
        )

    elif "region" in question:
        region = revenue_by_region.idxmax()
        revenue = revenue_by_region.max()

        return (
            f"The region with the highest revenue "
            f"is {region}, with "
            f"${revenue:,.2f}."
        )

    elif "category" in question:
        category = revenue_by_category.idxmax()
        revenue = revenue_by_category.max()

        return (
            f"The highest revenue category is "
            f"{category}, with "
            f"${revenue:,.2f}."
        )

    else:
        return (
            "I can currently answer questions about "
            "revenue, orders, customers, products, "
            "regions, categories, and average order value."
        )

In [24]:
def stream_response(text, delay=0.04):

    words = text.split()

    for word in words:
        print(word, end=" ", flush=True)
        time.sleep(delay)

    print()

In [25]:
question = "What is the total revenue?"

print("You:", question)
print("\nMetricMind:")

response = metricmind_response(question)

stream_response(response)

You: What is the total revenue?

MetricMind:
The total revenue is $81,355.00.

In [26]:
print("======================================")
print("        METRICMIND CHAT")
print("======================================")
print("Type 'exit' to stop.")
print()

while True:

    question = input("You: ")

    if question.lower() == "exit":
        print("MetricMind: Goodbye!")
        break

    response = metricmind_response(question)

    print("MetricMind:", end=" ")

    stream_response(response)

======================================
        METRICMIND CHAT
======================================
Type 'exit' to stop.

You:  How many orders do we have?

MetricMind: There are 15 total orders.

You:  Which category has the highest revenue?

MetricMind: The highest revenue category is AI, with $25,500.00.

You:  exit

MetricMind: Goodbye!

In [27]:
sales_model.to_csv(
    "metricmind_transformed_sales.csv",
    index=False
)

print(
    "Transformed sales model saved successfully!"
)

Transformed sales model saved successfully!

In [28]:
print("=" * 60)
print("       METRICMIND - WEEK 1 COMPLETION CHECK")
print("=" * 60)

print("✓ Mock corporate data created")
print("✓ Raw data layer created")
print("✓ Customer transformation completed")
print("✓ Product transformation completed")
print("✓ Order transformation completed")
print("✓ Sales model created")
print("✓ Business metrics created")
print("✓ Data quality checks completed")
print("✓ Revenue analysis completed")
print("✓ Chat scaffolding created")
print("✓ Streaming response implemented")
print("✓ Transformed data exported")

print("=" * 60)
print("             WEEK 1 COMPLETE")
print("=" * 60)

============================================================
       METRICMIND - WEEK 1 COMPLETION CHECK
============================================================
✓ Mock corporate data created
✓ Raw data layer created
✓ Customer transformation completed
✓ Product transformation completed
✓ Order transformation completed
✓ Sales model created
✓ Business metrics created
✓ Data quality checks completed
✓ Revenue analysis completed
✓ Chat scaffolding created
✓ Streaming response implemented
✓ Transformed data exported
============================================================
             WEEK 1 COMPLETE
============================================================